export const actionTypes = {
        
    GET_CUSTOMERS: 'GET_CUSTOMERS',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    GET_CUSTOMER_DETAILS: 'GET_CUSTOMER_DETAILS',
    UPDATE_CUSTOMER_NOTE: 'UPDATE_CUSTOMER_NOTE',
    UPDATE_CUSTOMER_STATUS: 'UPDATE_CUSTOMER_STATUS',
    CREATE_CUSTOMER_NOTE: 'CREATE_CUSTOMER_NOTE'
}